[package]
name = "bitblazr-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { version = "0.12", optional = true }
no-std-net = "0.6"

[lib]
path = "src/lib.rs"

